drop table iF EXISTS bookings;

drop table iF EXISTS comments;

drop table iF EXISTS items;

drop table iF EXISTS requests;

drop table iF EXISTS users;


CREATE SCHEMA IF NOT EXISTS schema;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT AK_email UNIQUE(email)
    );



CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    available BOOLEAN                                 NOT NULL,
    owner_id     BIGINT                                  NOT NULL REFERENCES users (id) on delete cascade
    );

CREATE TABLE IF NOT EXISTS bookings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id     BIGINT                            NOT NULL REFERENCES users (id) on delete cascade,
    item_id     BIGINT                            NOT NULL REFERENCES items (id) on delete cascade,
    status      VARCHAR(255)                      NOT NULL,
    start_booking TIMESTAMP                       NOT NULL,
    end_booking   TIMESTAMP                       NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id     BIGINT                            NOT NULL REFERENCES users (id) on delete cascade,
    item_id     BIGINT                            NOT NULL REFERENCES items (id) on delete cascade,
    text      VARCHAR(511)                      NOT NULL,
    created   TIMESTAMP                         NOT NULL
    );

